# Generated by Django 5.2.7 on 2025-12-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
