# Generated by Django 5.2.7 on 2025-12-08 16:01

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.utils.avatar_upload_path),
        ),
    ]
